# Generated by Django 4.1.7 on 2023-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_alter_car_db_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_db',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
