# Generated by Django 4.1.7 on 2023-05-25 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_alter_car_db_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_db',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
