# Generated by Django 4.1.7 on 2023-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0005_category_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_db',
            name='car_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
