# Generated by Django 4.1.7 on 2023-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0010_alter_car_db_body_style_alter_car_db_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_db',
            name='is_new',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
