# Generated by Django 4.1.7 on 2023-06-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0011_car_db_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_db',
            name='is_new',
        ),
    ]
