# Generated by Django 4.1.7 on 2023-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
