# Generated by Django 4.1.7 on 2023-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestDriveDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_day', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening')], max_length=20)),
                ('preferred_contact', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=10)),
            ],
        ),
    ]
