# Generated by Django 4.1.7 on 2023-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0003_enquirydb_testdrivedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrivedb',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
