# Generated by Django 4.1.7 on 2023-06-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0004_alter_testdrivedb_preferred_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdrivedb',
            name='preferred_contact',
        ),
    ]
