# Generated by Django 4.1.7 on 2023-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0005_remove_testdrivedb_preferred_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivedb',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
