# Generated by Django 4.1.7 on 2023-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0006_testdrivedb_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydb',
            name='car_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testdrivedb',
            name='car_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
