# Generated by Django 4.1.7 on 2023-06-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0007_enquirydb_car_id_testdrivedb_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydb',
            name='car_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
