# Generated by Django 4.1.7 on 2023-06-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0012_remove_car_db_is_new'),
        ('Web_Pages', '0008_enquirydb_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(blank=True, max_length=10, null=True)),
                ('carname', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('car_price', models.IntegerField()),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('milage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.car_db')),
            ],
        ),
    ]
