# Generated by Django 4.1.7 on 2023-06-26 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0010_compare_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydb',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='enquirydb',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Compare',
        ),
    ]
