# Generated by Django 4.1.7 on 2023-07-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Pages', '0011_enquirydb_create_date_enquirydb_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
